### PR TITLE
Update deps, syntax, usage

### PR DESCRIPTION
**Pull request by Dazix**
- update all deps to latest versions
- update plugin syntax for postCss v8+
- allow pass scope as object (because postcss+webpack)

### CODE REVIEW

**Comment by lindseyfont** [comment]
Is there any ETA for when this will be merged? We are looking to upgrade this as a dependency because of a security vulnerability, but this is blocking.

**Comment by Dazix** [comment]
@lindseyfont we already give it up and create fork and our own package.

**Comment by lindseyfont** [comment]
@Dazix Bummer. Do you also have it published as an `npm` package? We might just end up doing the same.

**Comment by Dazix** [comment]
@lindseyfont we have it in private npm registry, but I can check if we are able to publish it into public registry.

**Comment by pazams** [comment]
Thanks for the contribution, and sorry for missing this :pray: 
Merging this now, and will release on npm by tomorrow EOD.

**Pull request merged**
